### ISSUE TITLE
Unable to run tests on the browser

### ISSUE THREAD

**Issue by rchavarria** [tddbin/es6katas.org#4] opened 2015-05-14 10:41 UTC
I visit [es6katas.org](http://es6katas.org), choose a kata and press "Run tests" button or click "CTRL + R" to run tests. But nothing happens. I don't see the results of any test executing.

The title of the page is *No-install TDD environment* and I cans see this two JavaScript errors every time I try to run the tests:

    Error in parsing value for 'width'.  Declaration dropped. spec-runner.html
    Error in parsing value for 'height'.  Declaration dropped. spec-runner.html

I've tried it on Firefox and Chrome.

**Comment by tddbin** [comment] 2015-05-14 12:48
Hi Ruben
Do you have some more details please, like OS, version, browser versions
and maybe a screenshot would be great. I can't reproduce it. Thanks
Wolfram
Am 14.05.2015 12:41 schrieb "ruben" <notifications@github.com>:

**Comment by rchavarria** [comment] 2015-05-14 14:40
OS: Windows 7
Firefox 37.0.2

But I think they don't are really important. I thought the error was on several katas, but today I was only able to reproduce it with the [block-scoping > const kata](http://tddbin.com/#?kata=es6/language/block-scoping/const).

![tddbin-no-running-tests](https://cloud.githubusercontent.com/assets/612688/7633854/5f069d92-fa57-11e4-8f49-71ce4173d2a0.png)

Playing with it, I came up with a way tests run: just comment lines 10 and 16 (ok, I know that's not the purpose of a kata): 

![tddbin-running-tests](https://cloud.githubusercontent.com/assets/612688/7633865/745a36ea-fa57-11e4-8d9b-2448ad07471b.png)

So, maybe, a JavaScript error prevent tests for running. An error message would be helpful.

Thanks for the answer.

**Comment by wolframkriesing** [comment] 2015-05-14 17:47
Thanks for finding this out ... very strange, definitely. Diving into it.

**Comment by wolframkriesing** [comment] 2015-05-14 19:38
It only occurs in FF (the new IE :) #scnr)

**Comment by wolframkriesing** [comment] 2015-05-14 19:59
fixed via https://github.com/tddbin/tddbin-frontend/commit/192710c062324c3d3b522cebaee7c45ce2f465b0
please verify. works in FF now. thanks for finding it!!!

**Closed by wolframkriesing** 2015-05-14 20:00 UTC

**Comment by rchavarria** [comment] 2015-05-16 08:34
Awesome! It looks great!
Thanks a lot for fixing it.

**Comment by rajanski** [comment] 2017-05-01 11:57
Hi i would like to reopen this issue.
I get the same title of the page "No-install TDD environment" when clicking on any kata on the landing page. 
Chrome debugger says: 

`Uncaught TypeError: s.default is not a function
    at Object.196.atomic (index.min.js:4)
    at o (index.min.js:1)
    at index.min.js:1
    at Object.204../_aceDefaultShortcuts (index.min.js:4)
    at o (index.min.js:1)
    at e (index.min.js:1)
    at index.min.js:1`

Tested it on Ubuntu Xenial, with Opera, Chrome, Firefox, all the same :-(
